services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: ${CONTAINER_NAME}_postgres
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       PGDATA: ${PGDATA}
    volumes:
      - postgres_data:${PGDATA}
    networks:
      - postgres_net
  
  sumManager:
    build:
      context: ./SubManager
      dockerfile: ./Dockerfile
    image: manager_img
    restart: always
    container_name: ${CONTAINER_NAME}_subManager
    volumes:
      - ./SubManager/config/prod.yaml:/app/config/prod.yaml
    env_file:
      - ./SubManager/.env
    ports:
      - 8080:8080
    networks:
      - postgres_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  postgres_net:
    driver: bridge